# Note that this file only exists because of the ZFS problem with SQLite.
# See https://github.com/atuinsh/atuin/issues/952
# In 30_misc.sh, we set ATUIN_CONFIG_DIR this folder if we are on a
# system that uses ZFS.

## enable or disable automatic sync
auto_sync = true

## enable or disable automatic update checks
update_check = false

## address of the sync server
sync_address = "https://atuin.lab.nijho.lt"
enter_accept = true

[stats]
# Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
 "git",
 "g",
 "uv",
]

[theme]
name = "autumn"

# [Filesystem] ZFS is known to have some issues with SQLite. Atuin uses SQLite heavily. 
# Fix recommended in https://github.com/atuinsh/atuin/issues/952
[daemon]
enabled = true
