max_bitrate = 30000
output_name = HDMI-A-1
global_prep_cmd = [{"do":"/home/basnijholt/.config/hypr/scripts/sunshine-mode.sh start","undo":"/home/basnijholt/.config/hypr/scripts/sunshine-mode.sh stop"}]
