#!/usr/bin/env bash

set -euo pipefail

target_dir="$HOME/.nano/syntax/system"
placeholder_file="$target_dir/00-placeholder.nanorc"

find_syntax_dir() {
  local nano_bin prefix candidate user_name

  user_name="${USER:-$(id -un 2>/dev/null || true)}"

  if nano_bin="$(command -v nano 2>/dev/null)"; then
    prefix="$(cd "$(dirname "$nano_bin")/.." && pwd)"
    candidate="$prefix/share/nano"
    if [[ -d "$candidate" ]] && compgen -G "$candidate/*.nanorc" > /dev/null; then
      printf '%s\n' "$candidate"
      return 0
    fi
  fi

  for candidate in \
    /opt/homebrew/share/nano \
    /usr/local/share/nano \
    /usr/share/nano \
    /run/current-system/sw/share/nano \
    "$HOME/.nix-profile/share/nano" \
    "/etc/profiles/per-user/$user_name/share/nano"
  do
    if [[ -d "$candidate" ]] && compgen -G "$candidate/*.nanorc" > /dev/null; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done

  return 1
}

write_placeholder() {
  mkdir -p "$target_dir"
  find "$target_dir" -maxdepth 1 -name '*.nanorc' -delete
  {
    echo "# Placeholder generated by scripts/install-nano-syntax.sh."
    echo "# Keeps ~/.nanorc include glob non-empty when no system syntax files are available."
  } > "$placeholder_file"
}

if ! source_dir="$(find_syntax_dir)"; then
  write_placeholder
  echo "[nano] No syntax definition directory found; created placeholder in $target_dir."
  exit 0
fi

mkdir -p "$target_dir"
find "$target_dir" -maxdepth 1 -name '*.nanorc' -delete

shopt -s nullglob
for syntax_file in "$source_dir"/*.nanorc; do
  ln -sf "$syntax_file" "$target_dir/$(basename "$syntax_file")"
done

echo "[nano] Linked syntax definitions from $source_dir to $target_dir."
