#!/usr/bin/env python3

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HOOK_NAMES = ("pre-commit", "commit-msg")
HOOK_MARKER = "# git-forbidden-words-hook"
PRE_COMMIT_MARKER = "# File generated by pre-commit"
MAX_DISCOVERY_DEPTH = 5
PRUNED_DIRECTORIES = {
    ".cache",
    ".git",
    ".local",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    "target",
    "venv",
}


def discover_repositories(root: Path) -> list[Path]:
    repositories: set[Path] = set()
    root = root.resolve()
    for child in root.iterdir():
        if child.is_dir() and path_present(child / ".git"):
            repositories.add(child.resolve())
    for directory, child_directories, files in os.walk(root):
        current = Path(directory)
        if ".git" in child_directories or ".git" in files:
            repositories.add(current.resolve())
        depth = len(current.relative_to(root).parts)
        if depth >= MAX_DISCOVERY_DEPTH:
            child_directories.clear()
            continue
        child_directories[:] = [
            name
            for name in child_directories
            if name not in PRUNED_DIRECTORIES and not name.startswith(".")
        ]
    return sorted(repositories)


def hooks_directory(repository: Path) -> Path:
    result = subprocess.run(
        ["git", "-C", str(repository), "rev-parse", "--git-common-dir"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"not a Git repository: {repository}")
    common_directory = Path(result.stdout.strip())
    if not common_directory.is_absolute():
        common_directory = repository / common_directory
    return common_directory.resolve() / "hooks"


def file_contains(path: Path, marker: str) -> bool:
    try:
        return marker in path.read_text(errors="replace")
    except OSError:
        return False


def path_present(path: Path) -> bool:
    return path.exists() or path.is_symlink()


def companion_path(hook: Path, suffix: str) -> Path:
    return hook.with_name(f"{hook.name}.{suffix}")


def validate_install(hook: Path) -> None:
    if not path_present(hook) or file_contains(hook, HOOK_MARKER):
        return
    local_hook = companion_path(hook, "local")
    if file_contains(hook, PRE_COMMIT_MARKER):
        legacy_hook = companion_path(hook, "legacy")
        if (
            path_present(legacy_hook)
            and not file_contains(legacy_hook, HOOK_MARKER)
            and path_present(local_hook)
        ):
            raise RuntimeError(f"cannot preserve both {legacy_hook} and {local_hook}")
    elif path_present(local_hook):
        raise RuntimeError(f"refusing to replace existing hook backup: {local_hook}")


def copy_hook(source: Path, destination: Path) -> None:
    descriptor, temporary_name = tempfile.mkstemp(
        dir=destination.parent, prefix=f".{destination.name}.", suffix=".tmp"
    )
    os.close(descriptor)
    temporary = Path(temporary_name)
    try:
        shutil.copy2(source, temporary)
        temporary.chmod(temporary.stat().st_mode | 0o111)
        temporary.replace(destination)
    finally:
        temporary.unlink(missing_ok=True)


def install_hook(source: Path, hook: Path) -> None:
    if not path_present(hook):
        copy_hook(source, hook)
        return
    if file_contains(hook, HOOK_MARKER):
        copy_hook(source, hook)
        return
    local_hook = companion_path(hook, "local")
    if file_contains(hook, PRE_COMMIT_MARKER):
        legacy_hook = companion_path(hook, "legacy")
        if file_contains(legacy_hook, HOOK_MARKER):
            copy_hook(source, legacy_hook)
            return
        if path_present(legacy_hook):
            legacy_hook.replace(local_hook)
        try:
            copy_hook(source, legacy_hook)
        except OSError:
            if path_present(local_hook):
                local_hook.replace(legacy_hook)
            raise
        return
    hook.replace(local_hook)
    try:
        copy_hook(source, hook)
    except OSError:
        if file_contains(hook, HOOK_MARKER):
            hook.unlink()
        local_hook.replace(hook)
        raise


def repository_hooks(repository: Path) -> list[Path]:
    destination_directory = hooks_directory(repository)
    return [destination_directory / name for name in HOOK_NAMES]


def install_repository(template_hooks: Path, destinations: list[Path]) -> None:
    destinations[0].parent.mkdir(parents=True, exist_ok=True)
    for destination in destinations:
        install_hook(template_hooks / destination.name, destination)


def main(arguments: list[str]) -> int:
    root = Path(__file__).resolve().parents[1]
    template_hooks = root / "configs/git/template/hooks"
    if arguments:
        repositories = [Path(argument).resolve() for argument in arguments]
    else:
        repositories = discover_repositories(Path.home())
    sources = [template_hooks / name for name in HOOK_NAMES]
    for source in sources:
        if not source.is_file() or not os.access(source, os.R_OK):
            raise RuntimeError(f"hook template is not readable: {source}")
    unique_sets: dict[Path, list[Path]] = {}
    for repository in repositories:
        destinations = repository_hooks(repository)
        unique_sets[destinations[0].parent] = destinations
    installation_sets = list(unique_sets.values())
    for destinations in installation_sets:
        directory = destinations[0].parent
        writable_directory = directory if directory.exists() else directory.parent
        if not writable_directory.is_dir() or not os.access(
            writable_directory, os.W_OK
        ):
            raise RuntimeError(f"hook directory is not writable: {directory}")
        for destination in destinations:
            validate_install(destination)
    for destinations in installation_sets:
        install_repository(template_hooks, destinations)
    print(f"Installed forbidden-word hooks in {len(installation_sets)} repositories")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
