#!/usr/bin/env sh
# git-forbidden-words-hook
set -eu

case "$0" in
    *.legacy) local_hook="${0%.legacy}.local" ;;
    *) local_hook="${0}.local" ;;
esac
if [ -x "${local_hook}" ]; then
    "${local_hook}" "$@"
fi

"${HOME}/.config/git/forbidden-words-hook" commit-msg "$@"
