#!/usr/bin/env bash
set -e

# =======================================================================================
# Pi 4 Direct SSD Installer (ZFS Root + nixos-raspberrypi)
# =======================================================================================
# Installs NixOS directly onto a Samsung T5 SSD using the nixos-raspberrypi flake
# for proper kernel/firmware/bootloader support.
#
# Prerequisites on your Linux PC:
#   boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
#   boot.supportedFilesystems = [ "zfs" ];
#
# Usage: ./hosts/pi4/install-ssd.sh (run from configs/nixos directory)
# =======================================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLAKE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

FLAKE_ATTR="pi4"
DISK_ID="/dev/disk/by-id/usb-Samsung_Portable_SSD_T5_1234567A666E-0:0"

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# --- Pre-flight Checks ---
log "Checking prerequisites..."

if [ "$EUID" -eq 0 ]; then
    error "Run as normal user (not root). Script will sudo when needed."
fi

if [ ! -e "$DISK_ID" ]; then
    error "Target disk not found: $DISK_ID\nPlug in the Samsung T5 SSD."
fi

if [ ! -f /proc/sys/fs/binfmt_misc/aarch64-linux ]; then
    error "aarch64 emulation not enabled. Add to config:\n  boot.binfmt.emulatedSystems = [ \"aarch64-linux\" ];"
fi

if ! grep -q zfs /proc/modules; then
    warn "ZFS module not loaded. Loading..."
    sudo modprobe zfs || error "Failed to load ZFS. Add to config:\n  boot.supportedFilesystems = [ \"zfs\" ];"
fi

log "Target: $DISK_ID"
echo -e "${RED}WARNING: ALL DATA ON THIS DISK WILL BE DESTROYED.${NC}"
read -p "Proceed? (y/N) " -n 1 -r
echo
[[ ! $REPLY =~ ^[Yy]$ ]] && error "Aborted."

# --- Step 1: Partition with Disko ---
log "Step 1: Partitioning with disko..."
sudo nix run github:nix-community/disko -- --mode disko "$SCRIPT_DIR/disko.nix"

# --- Step 2: Build the system ---
log "Step 2: Building NixOS system (aarch64)..."
nix build "$FLAKE_DIR#nixosConfigurations.${FLAKE_ATTR}.config.system.build.toplevel" --no-link
SYSTEM_PATH=$(nix path-info "$FLAKE_DIR#nixosConfigurations.${FLAKE_ATTR}.config.system.build.toplevel")
log "Built: $SYSTEM_PATH"

# --- Step 3: Install to /mnt ---
log "Step 3: Installing NixOS to /mnt..."

# nixos-install copies the closure and runs activation
# The activation may fail in cross-arch chroot, but files get copied
set +e
sudo nixos-install --system "$SYSTEM_PATH" --root /mnt --no-root-passwd 2>&1 | tee /tmp/nixos-install.log
INSTALL_EXIT=$?
set -e

if [ $INSTALL_EXIT -ne 0 ]; then
    warn "nixos-install exited with code $INSTALL_EXIT (common for cross-arch)"
    warn "Checking if files were copied..."
fi

if [ ! -d "/mnt/nix/store" ] || [ -z "$(ls -A /mnt/nix/store 2>/dev/null)" ]; then
    error "Installation failed: /mnt/nix/store is empty"
fi
log "Nix store populated successfully."

# --- Step 4: Populate bootloader ---
log "Step 4: Populating bootloader (firmware + extlinux)..."

# Get the populate command for firmware
FIRMWARE_CMD=$(nix eval --raw "$FLAKE_DIR#nixosConfigurations.${FLAKE_ATTR}.config.boot.loader.raspberryPi.firmwarePopulateCmd")

# Clear existing bootloader files
log "Clearing existing boot files..."
sudo rm -rf /mnt/boot/firmware/* /mnt/boot/extlinux /mnt/boot/nixos

log "Running firmware populate..."
sudo $FIRMWARE_CMD -c "$SYSTEM_PATH" -f /mnt/boot/firmware

# Manually populate boot partition (bootPopulateCmd pollutes with host system generations)
log "Populating boot partition manually..."

# Get kernel and initrd paths from the system
KERNEL_PATH=$(nix eval --raw "$FLAKE_DIR#nixosConfigurations.${FLAKE_ATTR}.config.boot.kernelPackages.kernel")
INITRD_PATH=$(nix eval --raw "$FLAKE_DIR#nixosConfigurations.${FLAKE_ATTR}.config.system.build.initialRamdisk")

# Extract the store hash prefixes for the kernel files
KERNEL_NAME=$(basename "$KERNEL_PATH")
INITRD_NAME=$(basename "$INITRD_PATH")

# Create directories
sudo mkdir -p /mnt/boot/nixos /mnt/boot/extlinux

# Copy kernel, initrd, and dtbs
log "Copying kernel..."
sudo cp "$KERNEL_PATH/Image" "/mnt/boot/nixos/${KERNEL_NAME}-Image"
log "Copying initrd..."
sudo cp "$INITRD_PATH/initrd" "/mnt/boot/nixos/${INITRD_NAME}-initrd"
log "Copying device trees..."
sudo cp -r "$KERNEL_PATH/dtbs" "/mnt/boot/nixos/${KERNEL_NAME}-dtbs"

# Generate clean extlinux.conf (no host system pollution)
log "Generating extlinux.conf..."
sudo tee /mnt/boot/extlinux/extlinux.conf > /dev/null << EOF
# Generated by install-ssd.sh for pi4

DEFAULT nixos-default

TIMEOUT 50
MENU TITLE ------------------------------------------------------------

LABEL nixos-default
  MENU LABEL NixOS - Default
  LINUX ../nixos/${KERNEL_NAME}-Image
  INITRD ../nixos/${INITRD_NAME}-initrd
  FDT ../nixos/${KERNEL_NAME}-dtbs/broadcom/bcm2711-rpi-4-b.dtb
  FDTDIR ../nixos/${KERNEL_NAME}-dtbs
  APPEND init=${SYSTEM_PATH}/init console=serial0,115200n8 console=tty1 nohibernate loglevel=7 lsm=landlock,yama,bpf
EOF

# Verify bootloader files
log "Verifying bootloader files..."
if ! sudo test -f /mnt/boot/firmware/config.txt; then
    error "config.txt missing from /mnt/boot/firmware"
fi
if ! sudo test -f /mnt/boot/extlinux/extlinux.conf; then
    error "extlinux.conf missing from /mnt/boot"
fi
if ! sudo test -f /mnt/boot/nixos/${KERNEL_NAME}-Image; then
    error "Kernel image missing from /mnt/boot/nixos"
fi
log "Bootloader verified."

# --- Step 5: Set ZFS bootfs property ---
log "Step 5: Setting ZFS bootfs property..."
sudo zpool set bootfs=zroot/root zroot
log "ZFS bootfs set to zroot/root"

# --- Step 6: Cleanup ---
log "Step 6: Cleanup..."
sudo umount -R /mnt || warn "Some mounts may need manual cleanup"
sudo zpool export zroot || warn "zpool export failed - may already be exported"

log "=============================================="
log "SUCCESS! Installation complete."
log ""
log "Next steps:"
log "  1. Unplug the Samsung T5 SSD"
log "  2. Connect to Raspberry Pi 4 (Blue USB 3.0 port)"
log "  3. Remove any SD card"
log "  4. Power on"
log ""
log "The Pi should boot and connect to WiFi automatically."
log "=============================================="
